version: "3.8"

services:
    plex-server:
        build:
            context: ../..
            dockerfile: ./docker.d/dockerfiles/plex.Dockerfile
        container_name: $COMPOSE_PROJECT_NAME-plex-server
        restart: always
        volumes:
            - "$PLEX_DATA_FOLDER/config:/config"
            - "$PLEX_DATA_FOLDER/transcode:/transcode"
            - "$PLEX_DATA_FOLDER/data:/data"
        environment:
            TZ: $TIMEZONE
            PLEX_CLAIM: $PLEX_CLAIM_TOKEN
            ADVERTISE_IP: $PLEX_ADVERTISE_IP
            PLEX_UID: $PLEX_USER
            PLEX_GID: $PLEX_USER
            VERSION: docker
        ports:
            - "32400:32400/tcp"
            - "32400:32400/udp"
            - "3005:3005/tcp"
            - "8324:8324/tcp"
            - "32469:32469/tcp"
            - "1900:1900/udp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
        networks:
            default:
                aliases:
                    - $COMPOSE_PROJECT_NAME-plex-server